[package]
name = "ncd-tauri"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
build = "build.rs"

[dependencies]
ncd-core = { path = "../crates/ncd-core" }
dirs = "5"
serde_json = { workspace = true }
tauri = "2"

[build-dependencies]
tauri-build = "2"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ncd-tauri"
path = "src/main.rs"
