name: Bug 反馈
description: 报告可能的 NapCat Desktop 异常行为
title: '[BUG] '
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        欢迎来到 NapCat Desktop 的 Issue Tracker！请填写以下表格来提交 Bug。
        在提交新的 Bug 反馈前，请确保您：
        * 已经搜索了现有的 issues，并且没有找到可以解决您问题的方法
        * 不与现有的某一 issue 重复
  - type: input
    id: system-version
    attributes:
      label: 系统版本
      description: 运行 NapCat Desktop 的系统版本
      placeholder: Windows 10 Pro Workstation 22H2
    validations:
      required: true
  - type: input
    id: napcat-desktop-version
    attributes:
      label: NapCat Desktop 版本
      description: 可在 NapCat Desktop 的首页找到
      placeholder: 1.0.0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么?
      description: 填写你认为的 NapCat Desktop 的不正常行为
    validations:
      required: true
  - type: textarea
    id: how-reproduce
    attributes:
      label: 如何复现
      description: 填写应当如何操作才能触发这个不正常行为
      placeholder: |
        1. xxx
        2. xxx
        3. xxx
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: 期望的结果?
      description: 填写你认为 NapCat Desktop 应当执行的正常行为
    validations:
      required: true
  - type: textarea
    id: napcat-log
    attributes:
      label: NapCat Desktop 运行日志
      description: 粘贴相关日志内容到此处
      render: shell
