[package]
name = "ncd-traits"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ncd-domain = { path = "../ncd-domain" }
async-trait = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1", features = ["sync"] }
tracing = "0.1"

[lints]
workspace = true
